import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { z } from "zod";
import { SpecManifestSchema } from "../../schemas.js";
import { defineMachine } from "../_base.js";
import {
  appendScratchpad,
  beginPipelineStep,
  endPipelineStep,
  loadPipeline,
  renderIdeaIssueMarkdown,
  sanitizeFilenameSegment,
} from "./_shared.js";

export default defineMachine({
  name: "research.spec_render",
  description:
    "Renders spec documents (build mode) or skips to issue generation (ingest mode). " +
    "Both modes write issue markdown files and a bridge manifest for the develop workflow.",
  inputSchema: z.object({
    runDir: z.string().min(1),
    stepsDir: z.string().min(1),
    issuesDir: z.string().min(1),
    scratchpadPath: z.string().min(1),
    pipelinePath: z.string().min(1),
    repoRoot: z.string().min(1),
    repoPath: z.string().default("."),
    mode: z.enum(["build", "ingest"]),
    domains: z.array(z.any()).default([]),
    decisions: z.array(z.any()).default([]),
    phases: z.array(z.any()).default([]),
    issueSpecs: z.array(z.any()),
    parsedDomains: z.array(z.any()).default([]),
    parsedDecisions: z.array(z.any()).default([]),
  }),

  async execute(input, ctx) {
    const {
      runDir,
      issuesDir,
      scratchpadPath,
      pipelinePath,
      repoRoot,
      repoPath,
      mode,
      issueSpecs,
    } = input;
    const scratchpadRelPath = path.relative(ctx.workspaceDir, scratchpadPath);
    const pipeline = loadPipeline(pipelinePath) || {
      version: 1,
      current: "spec_render",
      history: [],
      steps: {},
    };
    beginPipelineStep(pipeline, pipelinePath, scratchpadPath, "spec_render", {
      mode,
    });

    let specDir = null;

    if (mode === "build") {
      specDir = path.join(runDir, "spec");
      mkdirSync(path.join(specDir, "decisions"), { recursive: true });
      mkdirSync(path.join(specDir, "phases"), { recursive: true });

      // Overview
      writeFileSync(
        path.join(specDir, "01-OVERVIEW.md"),
        `<!-- spec-meta\nversion: 1\ndomain: overview\n-->\n\n# Overview\n\nArchitectural overview generated by spec-build.\n`,
        "utf8",
      );

      // Architecture
      writeFileSync(
        path.join(specDir, "02-ARCHITECTURE.md"),
        `<!-- spec-meta\nversion: 1\ndomain: architecture\n-->\n\n# Architecture\n\nHigh-level architecture and domain decomposition.\n`,
        "utf8",
      );

      // Domain docs
      const domains = input.domains || [];
      for (let i = 0; i < domains.length; i++) {
        const d = domains[i];
        const num = String(i + 3).padStart(2, "0");
        const slug = sanitizeFilenameSegment(d.name, {
          fallback: `domain-${i + 1}`,
        }).toUpperCase();
        writeFileSync(
          path.join(specDir, `${num}-${slug}.md`),
          `<!-- spec-meta\nversion: 1\ndomain: ${d.name}\n-->\n\n# ${d.name}\n\n${d.description || ""}\n`,
          "utf8",
        );
      }

      // Decisions
      const decisions = input.decisions || [];
      for (let i = 0; i < decisions.length; i++) {
        const dec = decisions[i];
        const num = String(i + 1).padStart(3, "0");
        const slug = sanitizeFilenameSegment(dec.title || dec.id, {
          fallback: `adr-${i + 1}`,
        });
        writeFileSync(
          path.join(specDir, "decisions", `ADR-${num}-${slug}.md`),
          `<!-- adr-meta\nstatus: ${dec.status || "proposed"}\n-->\n\n# ${dec.title || dec.id}\n\n${dec.rationale || ""}\n`,
          "utf8",
        );
      }

      // Phases
      const phases = input.phases || [];
      for (let i = 0; i < phases.length; i++) {
        const ph = phases[i];
        const num = String(i + 1).padStart(2, "0");
        const slug = sanitizeFilenameSegment(ph.title || ph.id, {
          fallback: `phase-${i + 1}`,
        });
        writeFileSync(
          path.join(specDir, "phases", `PHASE-${num}-${slug}.md`),
          `# ${ph.title || ph.id}\n\n${ph.description || ""}\n`,
          "utf8",
        );
      }

      // Spec manifest
      const specManifest = SpecManifestSchema.parse({
        specId: path.basename(runDir),
        version: 1,
        repoRoot,
        domains: domains.map((d, i) => ({
          name: d.name,
          docPath: `spec/${String(i + 3).padStart(2, "0")}-${sanitizeFilenameSegment(d.name, { fallback: `domain-${i + 1}` }).toUpperCase()}.md`,
        })),
        decisions: decisions.map((dec, i) => ({
          id: dec.id || `ADR-${String(i + 1).padStart(3, "0")}`,
          title: dec.title || dec.id,
          status: dec.status || "proposed",
          docPath: `spec/decisions/ADR-${String(i + 1).padStart(3, "0")}-${sanitizeFilenameSegment(dec.title || dec.id, { fallback: `adr-${i + 1}` })}.md`,
        })),
        phases: phases.map((ph, i) => ({
          id: ph.id || `phase-${i + 1}`,
          title: ph.title || ph.id,
          issueIds: ph.issueIds || [],
          docPath: `spec/phases/PHASE-${String(i + 1).padStart(2, "0")}-${sanitizeFilenameSegment(ph.title || ph.id, { fallback: `phase-${i + 1}` })}.md`,
        })),
        createdAt: new Date().toISOString(),
      });
      writeFileSync(
        path.join(specDir, "manifest.json"),
        `${JSON.stringify(specManifest, null, 2)}\n`,
        "utf8",
      );
    }

    // Shared: generate issue markdown files
    const generatedIssues = [];
    for (let i = 0; i < issueSpecs.length; i++) {
      const item = issueSpecs[i];
      const issueId = `SPEC-${String(i + 1).padStart(2, "0")}`;
      const title = String(item?.title || `Issue ${i + 1}`).trim();
      const slug = sanitizeFilenameSegment(title, {
        fallback: `issue-${i + 1}`,
      });
      const fileName = `${String(i + 1).padStart(2, "0")}-${slug}.md`;
      const issuePath = path.join(issuesDir, fileName);

      const issueMd = renderIdeaIssueMarkdown({
        issue: item,
        issueId,
        title,
        repoPath,
        pointers: "",
        scratchpadRelPath,
      });
      writeFileSync(issuePath, issueMd, "utf8");

      generatedIssues.push({
        id: issueId,
        title,
        filePath: path.relative(ctx.workspaceDir, issuePath),
        priority: String(item?.priority || "P2"),
        depends_on: Array.isArray(item?.depends_on)
          ? item.depends_on.map((d) => String(d || "").trim()).filter(Boolean)
          : [],
        difficulty: 3,
      });
    }

    // Write bridge manifest
    const bridgeDir = path.join(ctx.workspaceDir, ".coder", "local-issues");
    mkdirSync(bridgeDir, { recursive: true });
    const bridgeManifestPath = path.join(bridgeDir, "manifest.json");
    const bridgeManifest = {
      repoRoot,
      issues: generatedIssues,
    };
    writeFileSync(
      bridgeManifestPath,
      `${JSON.stringify(bridgeManifest, null, 2)}\n`,
      "utf8",
    );

    endPipelineStep(
      pipeline,
      pipelinePath,
      scratchpadPath,
      "spec_render",
      "completed",
      { mode, issueCount: generatedIssues.length },
    );

    appendScratchpad(scratchpadPath, "Spec Render", [
      `- mode: ${mode}`,
      `- issueCount: ${generatedIssues.length}`,
      ...(specDir
        ? [`- specDir: ${path.relative(ctx.workspaceDir, specDir)}`]
        : []),
      `- bridgeManifest: ${path.relative(ctx.workspaceDir, bridgeManifestPath)}`,
    ]);

    ctx.log({
      event: "spec_render_complete",
      mode,
      issueCount: generatedIssues.length,
    });

    return {
      status: "ok",
      data: {
        specDir: specDir ? path.relative(ctx.workspaceDir, specDir) : null,
        bridgeManifestPath: path.relative(ctx.workspaceDir, bridgeManifestPath),
        issueCount: generatedIssues.length,
        issues: generatedIssues,
      },
    };
  },
});
